name: Drift check
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-for-changes:
    name: Check for changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node v16
        if: steps.changes.outputs.src == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_DEPLOY_SA_KEY }}
          project_id: bjerk-core

      - run: yarn install

      - uses: pulumi/actions@v3
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
        with:
          command: preview
          refresh: true
          stack-name: bjerk/prod
          expect-no-changes: true

      - uses: wearerequired/slack-messaging-action@v1
        if: failure()
        with:
          bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: infra-drifts-notifications
          payload: >-
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Drift-check is *failing* on ${{ github.repository_owner }}/${{ github.repository }}"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "#*${{ github.run_number }}*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Status: *${{ job.status }}*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Job: *${{ github.workflow }}*"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Go to job →",
                        "emoji": true
                      },
                      "value": "go-to-job",
                      "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                      "action_id": "go-to-job-action"
                    }
                  ]
                }
              ]
            }
