name: Drift check
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-for-changes:
    name: Check for changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOOGLE_DEPLOY_SA_KEY }}
          project_id: bjerk-core
          export_default_credentials: true
      - run: yarn install
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - uses: pulumi/actions@v3
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
        with:
          command: preview
          refresh: true
          stack-name: bjerk/prod
          expect-no-changes: true
      - uses: wearerequired/slack-messaging-action@v1
        if: failure()
        with:
          bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: infra-drifts-notifications
          payload: >-
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Drift-check is *failing* on ${{ github.repository_owner }}/${{ github.repository }}"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "#*${{ github.run_number }}*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Status: *${{ job.status }}*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Job: *${{ github.workflow }}*"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Go to job →",
                        "emoji": true
                      },
                      "value": "go-to-job",
                      "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                      "action_id": "go-to-job-action"
                    }
                  ]
                }
              ]
            }
