name: Drift check
on:
  schedule:
    # Run every day at 12 PM Europe/Oslo time
    - cron: '0 12 * * *'

jobs:
  check-for-changes:
    name: Check for changes (${{ matrix.project }} @ ${{ matrix.stack-name }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - project: core-infra
            stack-name: bjerk/conf
          - project: bjerk-io
            stack-name: bjerk/conf

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - name: Use Node LTS ✨
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Authenticate with Google 🔑
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - uses: cobraz/setup-gke-gcloud-auth-plugin@v1

      - name: Install dependencies 📦️
        run: pnpm install --frozen-lockfile

      - name: Run Pulumi 🚀
        uses: pulumi/actions@v4
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          command: preview
          refresh: true
          stack-name: ${{ matrix.stack-name }}
          workdir: projects/${{ matrix.project }}
          expect-no-changes: true

      - uses: wearerequired/slack-messaging-action@v2
        if: failure()
        with:
          bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: bjerk-notifications
          payload: >-
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Drift-check is *failing* on ${{
            github.repository_owner }}/${{ github.repository }}"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "#*${{ github.run_number }}*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Status: *${{ job.status }}*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Job: *${{ github.workflow }}*"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Go to job →",
                        "emoji": true
                      },
                      "value": "go-to-job",
                      "url": "https://github.com/${{ github.repository
            }}/actions/runs/${{ github.run_id }}",
                      "action_id": "go-to-job-action"
                    }
                  ]
                }
              ]
            }
