name: Pull Request
on:
  pull_request:

jobs:
  preview-changes:
    name: Preview changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_DEPLOY_SA_KEY }}
          project_id: bjerk-core

      - run: yarn install

      - uses: pulumi/actions@v3
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
        with:
          command: preview
          refresh: true
          stack-name: bjerk/prod
          comment-on-pr: true
          github-token: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
